source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Starscream', '~> 0.9.2'
#pod 'FMDB'
pod 'Alamofire', '~> 1.2'
pod 'SwiftyJSON', '~> 2.2.0'
pod 'YouTubePlayer'
pod 'SDCycleScrollView','~> 1.3'
#pod 'Google/SignIn'
pod 'MJRefresh'
pod 'RealmSwift'
pod 'Bolts'
#pod 'HanekeSwift'